accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('delete/',views.delete,name='delete'),



]

posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name='posts'

urlpatterns = [
    path('stark/',views.index, name='index'),
    path('schedule/',views.schedule, name='schedule'),
    path('introduction/',views.introduction,name='introduction'),
    path('<int:pk>/',views.detail,name='detail'),
    path('listi/',views.list,name='list'),
    path('create/',views.create,name='create'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('<int:pk>/comments/',views.comments_create,name='comments_create'),
    path('comments/<int:pk>/delete/',views.comment_delete,name='comment_delete'),
    path('category/',views.category_list,name='category_list'),
    path('category/<int:pk>/',views.category,name='category'),






] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=20, null=False)

    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=140,blank=True)
    image=models.ImageField(blank=True)
    content=models.TextField()
    category = models.ForeignKey(Category, null=False, on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,blank=True,null=True)
    link = models.URLField(null=True,blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    content=models.TextField()
    image=models.ImageField(blank=True)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    link = models.URLField(null=True, blank=True)

    def __str__(self):
        a = '에 대한 답변'
        return self.post.title + a



class Key(models.Model):
    key_number=models.CharField(max_length=140)

posts/forms.py
from django import forms
from .models import Post,Comment,Key

class PostForm(forms.ModelForm) :
    title = forms.CharField(
        max_length=100,
        label='제목',
        help_text='제목은 12자이내로 작성해주세요.',
        widget=forms.TextInput(
            attrs={
                'class': 'my-input',
                 }
        )
    )

    content = forms.CharField(
        label='내용',
        help_text='자유롭게 작성해주세요.',
        widget=forms.Textarea(
            attrs={
                'row': 5,
                'col': 50,
            }
        )
    )

    class Meta:
        model = Post
        fields = ['title', 'content','category','image']

class CommentForm(forms.ModelForm) :
    content = forms.CharField(
        label='내용',
        help_text='자유롭게 작성해주세요.',
        widget=forms.Textarea(
            attrs={
                'row': 5,
                'col': 35,
            }
        )
    )

    class Meta :
        model = Comment
        fields=['content','image','link']


class KeyForm(forms.ModelForm):

    class Meta :
        model=Key
        fields=['key_number']

posts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Comment,Category
from .forms import PostForm,CommentForm,KeyForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages


def index(request) :
    return render(request,'posts/index.html')

def schedule(request) :
    return render(request, 'posts/schedule.html')

def introduction(request) :
    return render(request,'posts/introduction.html')


def list(request) :
    posts=Post.objects.order_by('-created_date')
    context={'posts':posts}
    return render(request,'posts/list.html',context)


def detail(request,pk):
    post=get_object_or_404(Post,pk=pk)
    context={'post':post}
    return render(request,'posts/detail.html',context)

@login_required
def create(request):
   if request.method=="POST" :
       form=PostForm(request.POST,request.FILES)
       if form.is_valid():
           post = form.save(commit=False)
           post.user=request.user
           post.save()
           return redirect('posts:list')

   else:
       form=PostForm()
       context = {'form':form}

   return render(request,'posts/create.html',context)

@login_required
def delete(request,pk) :
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated :
        if post.user == request.user :
           post= get_object_or_404(Post,pk=pk)
           post.delete()
           return redirect('posts:list')
    else :
        messages.add_message(request, messages.WARNING, '로그인이 필요합니다.')
        messages.warning(request, '로그인이 필요합니다.')
        return redirect('posts:list')


@login_required
def edit(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if post.user == request.user :
      post=get_object_or_404(Post,pk=pk)
      if request.method=="POST" :
          form=PostForm(request.POST,request.FILES,instance=post)
          if form.is_valid() :
             post = form.save(commit=False)
             post.user=request.user
             post.save()
             return redirect('posts:detail',pk=post.pk)

      else:
          form = PostForm(instance=post)
          context={'form':form}
          return render(request,'posts/create.html',context)

@login_required
def comments_create(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == "POST" :
        form = CommentForm(request.POST,request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()

            return redirect('posts:detail',pk=post.pk)
    else:
        form = CommentForm()
        context = {'form' : form,
                   'post': post
                   }
    return render(request,'posts/comment.html',context)


@login_required
def comment_delete(request,pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.method=="POST":
        if comment.user == request.user:
            comment.delete()
    return redirect('posts:detail',pk=comment.post.pk)



def category(request,pk):
    category=get_object_or_404(Category,pk=pk)
    context={'category':category}
    return render(request,'posts/category.html',context)

def category_list(request) :
    categorys=Category.objects.all()
    context={'categorys': categorys,
             }
    return render(request,'posts/category_list.html',context)

def key(request):

        if request.method == 'POST':
            form = KeyForm(request.POST, request.FILES)
            if form.is_valid():
                key = form.save(commit=False)
                key.save()
                number = request.POST.get('key_number')
                if number == 'tmj-advance-2102':
                    return redirect('posts:index')

        else:
            form = KeyForm()
            context = {'form': form}
            return render(request,'posts/key.html',context)

posts/templates/posts/category.html
{% extends 'base.html' %}

{% block content %}

<style>
    h1{
    background-color : Orange;
    color:White;
    }
   h5{color:YellowGreen;}
    h4{color:Grey;}
    h6{color:DimGrey;}


    </style>


<h1>카테고리 : {{ category.name }}</h1>
<br>
<h6>제목을 클릭하시면 자세한 내용을 보실 수 있습니다.</h6>
<h6>또한 작성자에 의해 편집 및 삭제 가능합니다.</h6>
<br>
<a href="{% url 'posts:index' %}"><h5>첫페이지로 가기</h5></a>
<br><br><hr>
{% if category.post_set.all %}
{% for post in category.post_set.all %}

<h4><a href="{% url 'posts:detail' pk=post.pk %}">{{ forloop.counter }}..{{ post.title }}</a></h4>

{% endfor %}
{% else %}
<h4>아직 새글이 등록되지 않았습니다.</h4>
{% endif %}
{% endblock %}

posts/templates/posts/category_list.html
{% extends 'base.html' %}

{% block content %}

<style>
    h1{
    background-color : Orange;
    color:White;
    }
   h5{color:YellowGreen;}
    h4{color:Grey;}
    h6{color:DimGrey;}


    </style>


<h1>카테고리 </h1>
<br>
<h6>제목을 클릭하시면 자세한 내용을 보실 수 있습니다.</h6>
<h6>또한 작성자에 의해 편집 및 삭제 가능합니다.</h6>
<br><br>
<a href="{% url 'posts:index' %}"><h5>첫페이지로 가기</h5></a>
<br><br><hr>

{% for category in categorys %}

<h4><a href="{% url 'posts:category' pk=category.pk %}">{{ category.name }}</a></h4><br>


{% endfor %}
{% endblock %}

posts/templates/posts/comment.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<style>
    h2{
    background-color : Orange;
    color:White;
    }

    a{color:White ;}
    h4,h5{color:Grey;}
    h6{color:DimGrey;}




</style>
<hr>
<h2> {{ post.title }}에 답하기 또는 댓글 달기</h2>
<br>
<form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <button class="btn btn-primary">저장하기</button>
</form>
{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<style>
  h1{
    background-color : Orange;
    color:White;
    }

    a{color: white;}
 h5{
    color:White;
    border:2px solid white;
    width:120px;
    height:35px;
    display:inline-block;
    background-color:SkyBLue;
    padding-top:5px ;
    text-align:center;
    margin-right:20px;
    border-radius:12px/12px;
        }
</style>
{% if request.resolver_match.url_name == 'create' %}
<h1>질문 사항을 올려주세요. </h1>
{% else %}
<h2>작성된 글을 수정할 수 있어요</h2>
{% endif %}
<h5><a href="{% url 'posts:index' %}">첫페이지</a></h5>
     <h5><a href="{% url 'accounts:logout' %}">로그 아웃</a></h5>

<br><br>
<h6 style="color:Orangered;">image 파일은 필수 항목이 아닙니다.</h6>
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% if request.resolver_match.url_name == 'edit' %}
 <h6 style="color:orangered;">img를 변경하시려면 파일선택만 하시면 되고, 삭제하시려면 취소에 표시하시면 됩니다. </h6>
    <button class="btn btn-primary">수정하기</button>
    {% else %}
    <button class="btn btn-primary">새글</button>
  {% endif %}
    <br><br>


</form>




{% endblock %}

posts/templates/posts/deleted.html
<h3>Comments</h3>

<br><br>
<table class="table">

      <thead class="thead-light">
         <tr>
             <th scope="col">작성번호</th>
             <th scope="col">작성자</th>
             <th scope="col">사진</th>
             <th scope="col">내용</th>
         </tr>
      </thead>

      <tbody>
        {% for comment in post.comment_set.all %}
        <tr>
            <th scope="row"> {{ comment.pk }} </th>

            <td>{{ comment.user }}</td>

          {% if comment.image %}

            <td><img src="{{ comment.image.url }}" width="50" ></td>
          {% else %}
            <td>no image here</td>
          {% endif %}

          <td>{{ comment.content|truncatechars:20 }}</td>

         </tr>
        {% endfor %}
      </tbody>
    </table>

posts/templates/posts/detail.html
{% extends 'base.html' %}


{% block content %}
<style>
    h2{
    background-color : Orange;
    color:White;
    }

    h3{
      background-color:DarkGray;
      border-bottom:solid 3px DarkGray;
      color: gold;
      width:350px;
      text-align : center;
      display:inline-block;
      margin-bottom:30px;

      }
    a{color:White ;}
    h4,h5{color:Grey;
          }
    h5{color:DimGrey;
    margin-botton:10px;}

    h6{
    color:RoyalBlue;
    border:2px solid white;
    width:300x;
    height:30px;
    display:inline-block;
    background-color:White;
    padding: 5x 30px;
    margin-right:20px;
    border-radius:8px/8px;
        }

.pic{float:left;
     margin-right:50px;

     padding-bottom:0px;}

h5{line-height:200%;
 background-color: palegoldenrod;
 padding-left:15px;
 width:100%;
 border:30px solid White;
 border-radius: 8px/8px;

 }

 .nav {
  background:White;
  height: 50px;
  width:100%;
  margin-left:0px;
  padding-top:10px;
  padding-right:20px;
}

.nav ul {
  height: 40px;
  list-style: none;
  margin: 0 auto;
  padding: 0px;
}

.nav ul li {
  color: White;
  display: inline-block;
  height: 20px;
  line-height:20px;
  list-style: none;
  padding-top:0px;

  padding-left:30px;
  transition: background .5s;
}




</style>

<h2> {{ post.title }}  <a href="{% url 'posts:index' %}" style="color:white;
font-size:20px; float:right; padding:10px;font-weight:bold;">첫페이지로 가기</a></h2>

<br>
<h6>작성시간 : {{ post.created_date }} </h6><h6>  작성자 : {{ post.user }}</h6><h6> 카테고리 :
  {{ post.category }} </h6>
<br><br>
<div class="pic">
{% if post.image %}
<p><img src="{{ post.image.url }}" width="300"></p>
  {% endif %}
</div>
<div class="core">
<h5 style="font-weight:bold;">  {{ post.content|linebreaksbr }}</h5>
    {% if post.link %}
    <br>
 <a href="{{ post.link }}"> <h5> 링크 : {{ post.link }}</h5></a>
    {% endif %}
</div>


<br>
<div class="set">


    <div class="nav">
<ul>
    <li>

<button class="btn btn-primary"><a href="{% url 'posts:edit' pk=post.pk %}">수정</a></button>

</li>
    <li>
<form action="{% url 'posts:delete' pk=post.pk  %}"  method="POST">
        {% csrf_token %}
<button class="btn btn-primary"> 삭제 </button>
</form>
    </li>

    <li>

 <a href="{% url 'posts:comments_create' pk=post.pk %}"> <button class="btn btn-primary">댓글 작성</button></a>


    </li>

</ul>
        작성자만이 질문 내용을 수정, 삭제 할 수 있습니다.
    </div>
</div>

<br>


<hr>
<h3> Answers or Comments </h3>

{% if post.comment_set.all %}
{% endif %}



{% for comment in post.comment_set.all %}
<br>
<p> 작성자..............{{ comment.user }}</p>
{% if comment.image %}
<p> <img src="{{ comment.image.url }}" width="200"></p>
{% endif %}
<h4 style="line-height:150%; font-size:22px;"> {{ comment.content|linebreaksbr }}</h4>
<a href="{{ comment.link }}" style="color:gray;"> 링크 : {{ comment.link }}</a>
<br><br>
<form action="/posts/comments/{{ comment.pk }}/delete/" method="POST">
    {% csrf_token %}
    <button class="btn btn-secondary">댓글 지우기</button>

</form>

<hr>
{% endfor %}






{% endblock %}

posts/templates/posts/index.html
{% load static %}


<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>턱관절 교육연구회</title>


<style>
 .nav {
  background:Darkgray;
  height: 50px;
  width: 90%;
  margin-left:50px;
}

.nav ul {
  height: 40px;
  list-style: none;
  margin: 0 auto;
  padding: 0;
}

.nav ul li {
  color: White;
  display: inline-block;
  height: 20px;
  line-height:20px;
  list-style: none;
  padding-top;0px;

  padding-left:100px;
  transition: background .5s;
}

a {color:White;}
a h3{color:;white;
    border:2px solid white;
    width:150px;
    height:30px;
    display:inline-block;
    background-color:SkyBLue;
    padding: 5px 30px;
    text-align:center;
    margin-left:50px;
    border-radius:15px/15px;
    }

h2{width:90%;
   height:100px;
   border:1px solid white;
   background: url( "{% static 'posts/images/sunset (2).jpg' %}" )no-repeat center center;
   background-size: cover;
   padding:200px 100px;
   color:dimgray;
    }

    h4{margin-left:50px;}


</style>
</head>

<h2><p>안녕하세요?<br>
 턱관절 교육연구회입니다.<br>
 홈페이지에 오신걸 환영합니다.</p></h2>




<div class="nav">
 <div class="container">
  <ul>
   <li><h3><a href="{% url 'posts:list' %}"> Q & A  게시판</a></h3></li>
   <li><h3><a href="{% url 'posts:create' %}"> Q & A 새글쓰기</a></h3></li>
   <li><h3><a href="{% url 'posts:schedule' %}">강연 일정 및 공지사항</a></h3></li>
   <li><h3><a href="{% url 'posts:introduction' %}">턱관절 교육연구회 소개</a></h3></li>
  </ul>
 </div>
</div>
<br>
<br>
<hr>

<h4> 게시판은 로그인이 필요하지 않습니다.</h4>
<h4 style="color:royalblue;font-size:20px;">가입신청은 어떠한 개인정보도 요구하지 않으며 작성글과 댓글을 타인이 수정 삭제 하지 못하는 용도로만 사용됩니다.</h4>
<hr>
<div class="enter">
{% if user.is_authenticated %}
<a href="{% url 'accounts:logout' %}"><h3>로그 아웃</h3></a>
<a href="{% url 'accounts:delete' %}"><h3>회원 탈퇴</h3></a>
 </form>

{% else %}
 <a href="{% url 'accounts:login' %}"><h3>로그인</h3></a>
 <a href="{% url 'accounts:signup' %}"> <h3>가입신청하기</h3></a>
{% endif %}
</div>

posts/templates/posts/introduction.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>

a {color:White;}
h5 a{
    border:2px solid white;
    width:170px;
    height:40px;
    display:inline-block;
    background-color:SkyBLue;
    padding: 7px 30px;
    margin-left:40px;
    border-radius:15px/15px;
    }

.page-middle{width:90%;
   height:100px;
   border:1px solid white;
   background: url( "{% static 'posts/images/cloud.jpg' %}" )no-repeat center center;
   background-size: cover;

   padding:50px 200px 400px 100px;
   color:dimgray;
    }




</style>
<div class="page-middle">
<h1>TMJ 연구회 </h1>
<br>
<br>
<h4> 저희 TMJ 교육 연구회는 2003년부터 활동해 왔으며...</h4>
<br>
<h4></h4>
<p></p>


<h4></h4>
</div>

<br><hr>
    <h5><a href="{% url 'posts:index' %}">첫페이지</a>
{% if user.is_authenticated %}
   <a href="{% url 'accounts:logout' %}">로그 아웃</a></h5>
{% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}"> 가입신청</a></h5>
{% endif %}
{% endblock %}

posts/templates/posts/key.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
{% load bootstrap4 %}

<body>
<br><br>
<h3 style="color:skyblue ;
           line-height:180%;"> 안녕하세요 <br> 턱관절 교육연구회에 오신것을 환영합니다.<br>
             강연에서 공지한 key number를 입력해주세요.</h3>
<h6 style="color:darkgray; font-weight:bold;">브라우저는 가급적 google chrome 또는 microsoft edge를 이용해주시기 바랍니다.</h6>

</body>
<br><br>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary float-right my-2"> send</button>

</form>

{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block content %}

<style>
    h1{
    background-color : Orange;
    color:White;
    }




   h4{
    color:Gray;
    border:2px solid white;
    width:250px;
    height:35px;
    display:inline-block;
    background-color:Gold;
    padding-top:3px;
    padding-left:10px;
    border-radius:5px/5px;
    font-size:19px;}




a{color: white;}
 h5{
    color:White;
    border:2px solid white;
    width:300x;
    height:30px;
    display:inline-block;
    background-color:SkyBLue;
    padding: 5x 30px;
        }


h6{color: blue; }

    </style>


<h1>게시판 목록</h1>
<br>
<h6 style="color:DimGray">제목을 클릭하시면 자세한 내용을 보실 수 있습니다.</h6>
<h6 style="color:DimGray">또한 작성자에 의해 편집 및 삭제 가능합니다.</h6>
<br>
<a href="{% url 'posts:index' %}"><h4>첫페이지로 가기</h4></a>

<a href="{% url 'posts:category_list' %}"><h4> 카테고리별 질문목록</h4></a>

<br><br>
<table class="table">

      <thead class="thead-light">
        <tr>
          <th scope="col">작성번호</th>
          <th scope="col">제목</th>
            <th scopte="col">사진</th>
            <th scopre="col">내용</th>
          <th scope="col">작성 시간</th>
            <th scope="col">카테고리</th>

        </tr>
      </thead>
      <tbody>
       {% for post in posts %}
        <tr>
          <th scope="row">{{ post.pk }}</th>

           <td><h5><a href="{% url 'posts:detail' pk=post.pk %}">{{ post.title }}</a></h5></td>
             {% if post.image %}
           <td><img src="{{ post.image.url }}" width="30" ></td>
            {% else %}
             <td></td>
            {% endif %}
            <td> {{ post.content|truncatechars:15 }}</td>
          <td>{{ post.created_date }}</td>
            <td> <a href="{% url 'posts:category' pk=post.category.pk %}"><h6>{{ post.category }}</h6></td>

        </tr>
        {% endfor %}
      </tbody>
    </table>

<br><br>



{% endblock %}

posts/templates/posts/schedule.html
{% extends 'base.html' %}
{% block css %}

    <style>
        body { color:Grey;}


    </style>


{% endblock %}

{% block content %}
<style>
    h1{
    background-color : Orange;
    color:White;
    padding-left:30px;
    }


    h4{color:Grey;}
    h3{color:DimGrey;}

a {color:White;}
h5 a{
    border:2px solid white;
    border-radius:15px/15px;
    width:170px;
    height:40px;
    display:inline-block;
    background-color:SkyBLue;
    padding: 7px 30px;
    margin-right:40px;
    }



</style>

<h1> 강연일정</h1>
<br>
<br>

<hr>
<h3> 날짜 :   2021년 OO월 OO일 일요일</h3><br>
<h3> 시간 :  오전 10시 ~ 오후 6시</h3><br>
<h3> 장소 : 서울역  OO 아트홀</h3><br>
<h3> 점심시간 : 12시 ~ 1시 </h3><br>
<hr>
<h3>O월 OO일에 뵙겠습니다 ^^.</h3>

<hr>
    <h5><a href="{% url 'posts:index' %}">첫페이지</a>
{% if user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">로그 아웃</a></h5>
{% else %}
    <a href="{% url 'accounts:login' %}">로그인</a>
   <a href="{% url 'accounts:signup' %}"> 가입신청</a></h5>
{% endif %}

{% endblock %}